<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Innova.Domain\Innova.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="GuestManagement\Guest\DomainEventHandlers\"/>
        <Folder Include="GuestManagement\Guest\Queries\"/>
    </ItemGroup>

</Project>
