<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Billing\Exceptions\"/>
        <Folder Include="FrontDesk\Exceptions\"/>
        <Folder Include="HouseKeeping\Exceptions\"/>
        <Folder Include="Reservations\Exceptions\"/>
        <Folder Include="RoomInventory\Exceptions\"/>
    </ItemGroup>

</Project>
